version: '3.8'

services:
  fastapi-app:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fastapi-app.rule=Host(`localhost`)"
      - "traefik.http.services.fastapi-app.loadbalancer.server.port=8000"
    restart: always

  traefik:
    image: traefik:v2.9
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
